export const Vi = {
  customer: 'Khách hàng',
  staff: 'Nhân viên',
  product: 'Sản phẩm',
  importProduct: 'Nhập sản phẩm',
  createImportProduct: 'Tạo nhập sản phẩm',
  saleProducts: 'Chi tiết sản phẩm',
  brand: 'Hãng',
  supplier: 'Nhà cung cấp',
  service: 'Dịch vụ',
  receipt: 'Phiếu tiếp nhận',
  Quote: 'Phiếu báo giá',
  bill: 'Hoá đơn',
  addNewReceipt: 'Tạo phiếu tiếp nhận mới',
  addNewImportProduct: 'Tạo phiếu nhập mới',
  quote: 'Phiếu báo gía',
  inforQuote: 'Thông tin phiếu báo gía',
  inforImportProduct: 'Thông tin phiếu nhập',
  addNewCustomer: 'Tạo khách hàng mới',

  addNewStaff: 'Tạo nhân viên mới',

  addNewProduct: 'Tạo sản phẩm mới',
  addNewBrand: 'Tạo hãng mới',
  addNewSupplier: 'Tạo nhà cung cấp mới',
  addNewService: 'Tạo dịch vụ mới',
  nameProduct: 'Tên sản phẩm',
  priceProduct: 'Giá sản phẩm',
  nameCustomer: 'Tên khách hàng',
  nameStaff: 'Tên Nhân viên',
  emailCustomer: 'Email khách hàng',
  phoneCustomer: 'Số điện thoại khách hàng',
  phoneStaff: 'Số điện thoại ',
  costPrice: 'Gía gốc ',
  nameBrand: 'Tên hãng',
  nameSupplier: 'Tên nhà cung cấp',

  phoneNumberSupplier: 'Số điện thoại nhà cung cấp',

  addressSupplier: 'Địa chỉ nhà cung cấp',
  priceService: 'Giá dịch vụ',
  nameService: 'Tên dịch vụ',
  plateNumber: 'Biển số xe',
  createAt: 'Tạo lúc',
  descriptionReceipt: 'Mô tả đơn nhận',
  price: 'Giá',
  costPrice: 'Giá Nhập',
  status: 'Trạng thái',
  detail: 'Chi tiết',
  receiptId: 'Mã tiếp nhận',
  createAtReceipt: 'Ngày tiếp nhận',
  createName: 'Người tạo',
  vehicleInformation: 'Thông tin xe',
  quoteId: 'Mã phiếu báo gía',
  importProductId: 'Mã phiếu nhập',
  addProductService: 'Thêm sản phẩm vào phiếu nhập',
  //xe
  brandVehicle: 'Hãng xe',
  vehicleNumber: 'Biển số xe',
  vehicleColor: 'Màu xe',
  vehicleType: 'Mẫu xe',
  chassisNumber: 'Số khung xe',
  engineNumber: 'số máy ',
  vehicleCondition: 'Tình trạng xe',
  noteVehicle: 'Ghi chú',
  save: 'Lưu phiếu',
  reset: 'Làm mới',
  next: 'Tiến hành sửa chửa',
  Cancel: 'huỷ',

  ///
  productId: 'Mã sản phẩm',
  servicesId: 'Mã dịch vụ',
  quantity: 'số lượng',
  totalPrice: 'Thành tiền',
  add: 'Thêm ',
  Description: 'mô tả',
  address: 'Địa chỉ',
  role: 'Vai trò',
  userName: 'Tên tài khoản',
  autoRenderId: 'Hệ thống tự tạo',
  staffWork: 'Nhân viên sửa chửa',
  totalPriceImport: 'Tổng tiền',
  // Please enter full information: 'Nha'
};
